FROM docker.io/library/postgres
ENV POSTGRES_HOST_AUTH_METHOD trust
ENV PGDATA /var/lib/postgresql/data
#####################################################
COPY ./init-user-db.sql /docker-entrypoint-initdb.d/init-user-db.sql

